import type { Metadata } from "next";
import "./globals.css";
import {
  bodoniModa,
  italian,
  lexend,
  montserrat,
  notoSerifDisplay,
  redHatDisplay,
} from "@/lib/fonts";

export const metadata: Metadata = {
  title: {
    template: "%s | CH.LOE",
    default: "CH.LOE",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="summer">
      <body
        className={`${notoSerifDisplay.variable} ${bodoniModa.variable} ${italian.variable} ${lexend.variable} ${redHatDisplay.variable} ${montserrat.variable} antialiased bg-[#f9f9f9]`}
      >
        <div className="w-full h-screen">{children}</div>
      </body>
    </html>
  );
}
